// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinalSoft.Services;

#nullable disable

namespace ProyectoFinalSoft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240512154519_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompetenciaPrograma", b =>
                {
                    b.Property<int>("CompetenciascompetenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramasprogramaId")
                        .HasColumnType("int");

                    b.HasKey("CompetenciascompetenciaId", "ProgramasprogramaId");

                    b.HasIndex("ProgramasprogramaId");

                    b.ToTable("CompetenciaPrograma");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Ambiente", b =>
                {
                    b.Property<int>("ambienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ambienteId"));

                    b.Property<decimal>("ambienteCapacidad")
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("Ambiente_capacidad");

                    b.Property<string>("ambienteCodigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ambiente_Codigo");

                    b.Property<decimal>("ambienteEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Ambiente_estado");

                    b.Property<string>("ambienteNombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ambiente_Nombre");

                    b.Property<string>("ambienteTipo")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ambiente_tipo");

                    b.Property<string>("ambienteUbicacion")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Ambiente_ubicacion");

                    b.HasKey("ambienteId");

                    b.HasIndex("ambienteCodigo")
                        .IsUnique();

                    b.ToTable("Ambientes");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Competencia", b =>
                {
                    b.Property<int>("competenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("competenciaId"));

                    b.Property<decimal>("competenciaEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Competencia_Estado");

                    b.Property<string>("competenciaNombre")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Competencia_Nombre");

                    b.Property<string>("competenciaTipo")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Competencia_Tipo");

                    b.HasKey("competenciaId");

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Coordinador", b =>
                {
                    b.Property<int>("coordinadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("coordinadorId"));

                    b.Property<decimal>("coordinadorEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Coordinador_Estado");

                    b.Property<string>("coordinadorNombre")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Coordinador_Nombre");

                    b.HasKey("coordinadorId");

                    b.ToTable("Coordinador");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Docente", b =>
                {
                    b.Property<int>("docenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("docenteId"));

                    b.Property<string>("docenteApellido")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Docente_Apellido");

                    b.Property<string>("docenteArea")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Docente_Area");

                    b.Property<decimal>("docenteEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Docente_estado");

                    b.Property<string>("docenteNombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Docente_Nombre");

                    b.Property<string>("docenteNumId")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Docente_NumId");

                    b.Property<string>("docenteTipo")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Docente_Tipo");

                    b.Property<string>("docenteTipoContrato")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("Docente_TipoContraro");

                    b.Property<string>("docenteTipoId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Docente_TipoId");

                    b.HasKey("docenteId");

                    b.HasIndex("docenteNumId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Horario", b =>
                {
                    b.Property<int>("horarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("horarioId"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("ambienteId")
                        .HasColumnType("int");

                    b.Property<int?>("docenteId")
                        .HasColumnType("int");

                    b.Property<string>("horarioDia")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Horario_dia");

                    b.Property<decimal>("horarioDuracion")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Horario_duracion");

                    b.Property<decimal>("horarioEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Horario_estado");

                    b.Property<decimal>("horarioHoraFin")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("Horario_hora_fin");

                    b.Property<decimal>("horarioHoraInicio")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("Horario_hora_inicio");

                    b.Property<int?>("periodoAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("horarioId");

                    b.HasIndex("CompetenciaId");

                    b.HasIndex("ambienteId");

                    b.HasIndex("docenteId");

                    b.HasIndex("periodoAcademicoId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("periodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("periodoId"));

                    b.Property<decimal>("periodoEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Periodo_estado");

                    b.Property<DateOnly>("periodoFechaFin")
                        .HasColumnType("date")
                        .HasColumnName("Periodo_Fecha_Fin");

                    b.Property<DateOnly>("periodoFechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("Periodo_Fecha_Inicio");

                    b.Property<string>("periodoNombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Periodo_Nombre");

                    b.HasKey("periodoId");

                    b.ToTable("PeriodosAcademicos");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Programa", b =>
                {
                    b.Property<int>("programaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("programaId"));

                    b.Property<decimal>("programaEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Programa_Estado");

                    b.Property<string>("programaNombre")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Programa_Nombre");

                    b.HasKey("programaId");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Usuario", b =>
                {
                    b.Property<int>("usuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("usuarioId"));

                    b.Property<int?>("coordinadorId")
                        .HasColumnType("int");

                    b.Property<int?>("docenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("usuarioEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("usuario_estado");

                    b.Property<string>("usuarioLogin")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Usuario_login");

                    b.Property<string>("usuarioPassword")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Usuario_password");

                    b.HasKey("usuarioId");

                    b.HasIndex("coordinadorId")
                        .IsUnique();

                    b.HasIndex("docenteId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CompetenciaPrograma", b =>
                {
                    b.HasOne("ProyectoFinalSoft.Models.Competencia", null)
                        .WithMany()
                        .HasForeignKey("CompetenciascompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinalSoft.Models.Programa", null)
                        .WithMany()
                        .HasForeignKey("ProgramasprogramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Horario", b =>
                {
                    b.HasOne("ProyectoFinalSoft.Models.Competencia", "competencia")
                        .WithMany("Horarios")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinalSoft.Models.Ambiente", "ambiente")
                        .WithMany("Horarios")
                        .HasForeignKey("ambienteId");

                    b.HasOne("ProyectoFinalSoft.Models.Docente", "docente")
                        .WithMany("Horarios")
                        .HasForeignKey("docenteId");

                    b.HasOne("ProyectoFinalSoft.Models.PeriodoAcademico", "periodoAcademico")
                        .WithMany("Horarios")
                        .HasForeignKey("periodoAcademicoId");

                    b.Navigation("ambiente");

                    b.Navigation("competencia");

                    b.Navigation("docente");

                    b.Navigation("periodoAcademico");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoFinalSoft.Models.Coordinador", "coordinador")
                        .WithOne("usuario")
                        .HasForeignKey("ProyectoFinalSoft.Models.Usuario", "coordinadorId");

                    b.HasOne("ProyectoFinalSoft.Models.Docente", "docente")
                        .WithOne("usuario")
                        .HasForeignKey("ProyectoFinalSoft.Models.Usuario", "docenteId");

                    b.Navigation("coordinador");

                    b.Navigation("docente");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Ambiente", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Competencia", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Coordinador", b =>
                {
                    b.Navigation("usuario");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Docente", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
