// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinalSoft.Services;

#nullable disable

namespace ProyectoFinalSoft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240427171430_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinalSoft.Models.Ambiente", b =>
                {
                    b.Property<int>("ambienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ambienteId"));

                    b.Property<decimal>("ambienteCapacidad")
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("Ambiente_capacidad");

                    b.Property<decimal>("ambienteEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Ambiente_estado");

                    b.Property<string>("ambienteNombre")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ambiente_Nombre");

                    b.Property<string>("ambienteTipo")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Ambiente_tipo");

                    b.Property<string>("ambienteUbicacion")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Ambiente_ubicacion");

                    b.HasKey("ambienteId");

                    b.ToTable("Ambientes");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Docente", b =>
                {
                    b.Property<int>("docenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("docenteId"));

                    b.Property<string>("docenteApellido")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Docente_Apellido");

                    b.Property<string>("docenteArea")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Docente_Area");

                    b.Property<decimal>("docenteEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Docente_estado");

                    b.Property<string>("docenteNombre")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Docente_Nombre");

                    b.Property<string>("docenteNumId")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Docente_NumId");

                    b.Property<string>("docenteTipo")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Docente_Tipo");

                    b.Property<string>("docenteTipoContrato")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("Docente_TipoContraro");

                    b.Property<string>("docenteTipoId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Docente_TipoId");

                    b.HasKey("docenteId");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Horario", b =>
                {
                    b.Property<int>("horarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("horarioId"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("int");

                    b.Property<int?>("ambienteId")
                        .HasColumnType("int");

                    b.Property<int?>("docenteId")
                        .HasColumnType("int");

                    b.Property<string>("horarioDia")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Horario_dia");

                    b.Property<decimal>("horarioDuracion")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Horario_duracion");

                    b.Property<decimal>("horarioEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Horario_estado");

                    b.Property<decimal>("horarioHoraFin")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("Horario_hora_fin");

                    b.Property<decimal>("horarioHoraInicio")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("Horario_hora_inicio");

                    b.Property<int?>("periodoAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("horarioId");

                    b.HasIndex("ambienteId");

                    b.HasIndex("docenteId");

                    b.HasIndex("periodoAcademicoId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("periodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("periodoId"));

                    b.Property<decimal>("periodoEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("Periodo_estado");

                    b.Property<DateOnly>("periodoFechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("periodoFechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("periodoNombre")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Periodo_Nombre");

                    b.HasKey("periodoId");

                    b.ToTable("PeriodosAcademicos");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Usuario", b =>
                {
                    b.Property<int>("usuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("usuarioId"));

                    b.Property<int?>("docenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("usuarioEstado")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("usuario_estado");

                    b.Property<string>("usuarioLogin")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Usuario_login");

                    b.Property<string>("usuarioPassword")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Usuario_password");

                    b.HasKey("usuarioId");

                    b.HasIndex("docenteId")
                        .IsUnique()
                        .HasFilter("[docenteId] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Horario", b =>
                {
                    b.HasOne("ProyectoFinalSoft.Models.Ambiente", "ambiente")
                        .WithMany("Horarios")
                        .HasForeignKey("ambienteId");

                    b.HasOne("ProyectoFinalSoft.Models.Docente", "docente")
                        .WithMany("Horarios")
                        .HasForeignKey("docenteId");

                    b.HasOne("ProyectoFinalSoft.Models.PeriodoAcademico", "periodoAcademico")
                        .WithMany("Horarios")
                        .HasForeignKey("periodoAcademicoId");

                    b.Navigation("ambiente");

                    b.Navigation("docente");

                    b.Navigation("periodoAcademico");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoFinalSoft.Models.Docente", "docente")
                        .WithOne("usuario")
                        .HasForeignKey("ProyectoFinalSoft.Models.Usuario", "docenteId");

                    b.Navigation("docente");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Ambiente", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.Docente", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("ProyectoFinalSoft.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
